### YamlMime:UniversalReference
ms.openlocfilehash: c47bc44f8df649c0de0c415fbc7867bb18ecf5c3
ms.sourcegitcommit: efa2d98deffe8a0d41a8d63f9f07aa720862e6ab
ms.translationtype: MT
ms.contentlocale: ru-RU
ms.lasthandoff: 12/13/2018
ms.locfileid: "52125149"
items:
- uid: azure-servicefabric.ExecutingFaultsChaosEvent
  name: ExecutingFaultsChaosEvent
  fullName: ExecutingFaultsChaosEvent
  children:
  - azure-servicefabric.ExecutingFaultsChaosEvent.faults
  langs:
  - typeScript
  type: interface
  summary: Описывает события Chaos, которая создается при Chaos приняла решение о сбое для итерации. Это событие Chaos содержит сведения о сообщения об ошибках как список строк.
  extends:
    name: azure-servicefabric.ChaosEvent
  package: azure-servicefabric
- uid: azure-servicefabric.ExecutingFaultsChaosEvent.faults
  name: faults
  fullName: faults
  children: []
  langs:
  - typeScript
  type: property
  summary: Список строковое описание ошибки, которые Chaos решил выполнить в ходе итерации.
  optional: true
  syntax:
    content: 'faults?: string[]'
    return:
      type:
      - string[]
  package: azure-servicefabric
references:
- uid: azure-servicefabric.ChaosEvent
  name: ChaosEvent
  spec.typeScript:
  - name: ChaosEvent
    fullName: ChaosEvent
    uid: azure-servicefabric.ChaosEvent
