### YamlMime:UniversalReference
items:
  - uid: azure-servicefabric.TestErrorChaosEvent
    name: TestErrorChaosEvent
    fullName: TestErrorChaosEvent
    children:
      - azure-servicefabric.TestErrorChaosEvent.kind
      - azure-servicefabric.TestErrorChaosEvent.reason
      - azure-servicefabric.TestErrorChaosEvent.timeStampUtc
    langs:
      - typeScript
    type: interface
    summary: |-
      <span data-ttu-id="e075f-101">Описывает события Chaos, которая создается при возникновении непредвиденных события в модуле Chaos.</span><span class="sxs-lookup"><span data-stu-id="e075f-101">Describes a Chaos event that gets generated when an unexpected event occurs in the Chaos engine.</span></span>
      <span data-ttu-id="e075f-102">Например из-за моментального снимка кластера, не согласована, во время сущности с ошибками, Chaos найти что сущность уже сбой — что было бы непредвиденное событие.</span><span class="sxs-lookup"><span data-stu-id="e075f-102">For example, due to the cluster snapshot being inconsistent, while faulting an entity, Chaos found that the entity was already faulted -- which would be an unexpected event.</span></span>
    extends:
      name: azure-servicefabric.ChaosEvent
    package: azure-servicefabric
  - uid: azure-servicefabric.TestErrorChaosEvent.kind
    name: kind
    fullName: kind
    children: []
    langs:
      - typeScript
    type: property
    summary: <span data-ttu-id="e075f-103">Полиморфные дискриминатора</span><span class="sxs-lookup"><span data-stu-id="e075f-103">Polymorphic Discriminator</span></span>
    syntax:
      content: 'kind: string'
      return:
        type:
          - string
    package: azure-servicefabric
  - uid: azure-servicefabric.TestErrorChaosEvent.reason
    name: reason
    fullName: reason
    children: []
    langs:
      - typeScript
    type: property
    summary: '<span data-ttu-id="e075f-104">Описывает, почему TestErrorChaosEvent был создан.</span><span class="sxs-lookup"><span data-stu-id="e075f-104">Describes why TestErrorChaosEvent was generated.</span></span> <span data-ttu-id="e075f-105">К примеру Chaos пытается сбоя секции, но обнаруживает, что раздел больше не является отказоустойчивым, а затем получает созданный TestErrorEvent причина сообщение о том, что раздел не является отказоустойчивым.</span><span class="sxs-lookup"><span data-stu-id="e075f-105">For example, Chaos tries to fault a partition but finds that the partition is no longer fault tolerant, then a TestErrorEvent gets generated with the reason stating that the partition is not fault tolerant.</span></span>'
    optional: true
    syntax:
      content: 'reason?: string'
      return:
        type:
          - string
    package: azure-servicefabric
  - uid: azure-servicefabric.TestErrorChaosEvent.timeStampUtc
    name: timeStampUtc
    fullName: timeStampUtc
    children: []
    langs:
      - typeScript
    type: property
    summary: '<span data-ttu-id="e075f-106">Отметка времени в формате UTC, когда было создано данное событие Chaos.</span><span class="sxs-lookup"><span data-stu-id="e075f-106">The UTC timestamp when this Chaos event was generated.</span></span>'
    syntax:
      content: 'timeStampUtc: Date'
      return:
        type:
          - Date
    package: azure-servicefabric
references:
  - uid: azure-servicefabric.ChaosEvent
    name: ChaosEvent
    spec.typeScript:
      - name: ChaosEvent
        fullName: ChaosEvent
        uid: azure-servicefabric.ChaosEvent