### YamlMime:UniversalReference
ms.openlocfilehash: 80639ea90d12b3e57b99dc309a62df521d35f0f5
ms.sourcegitcommit: efa2d98deffe8a0d41a8d63f9f07aa720862e6ab
ms.translationtype: MT
ms.contentlocale: ru-RU
ms.lasthandoff: 12/13/2018
ms.locfileid: "52032699"
items:
- uid: azure-servicefabric.ValidationFailedChaosEvent
  name: ValidationFailedChaosEvent
  fullName: ValidationFailedChaosEvent
  children:
  - azure-servicefabric.ValidationFailedChaosEvent.reason
  langs:
  - typeScript
  type: interface
  summary: Событие chaos, соответствующий сбоя во время проверки.
  extends:
    name: azure-servicefabric.ChaosEvent
  package: azure-servicefabric
- uid: azure-servicefabric.ValidationFailedChaosEvent.reason
  name: reason
  fullName: reason
  children: []
  langs:
  - typeScript
  type: property
  summary: Описывает, почему ValidationFailedChaosEvent был создан. Это может произойти, потому что больше, чем MaxPercentUnhealthyNodes находятся в неработоспособном состоянии дольше, чем MaxClusterStabilizationTimeout. Поэтому будет в свойстве причина ValidationFailedChaosEvent как строка.
  optional: true
  syntax:
    content: 'reason?: string'
    return:
      type:
      - string
  package: azure-servicefabric
references:
- uid: azure-servicefabric.ChaosEvent
  name: ChaosEvent
  spec.typeScript:
  - name: ChaosEvent
    fullName: ChaosEvent
    uid: azure-servicefabric.ChaosEvent
